export const GET_CART = "GET_CART";
export const DELETE_FROM_CART= "DELETE_FROM_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_TOTAL_AMOUNT_OF_CART = "GET_TOTAL_AMOUNT_OF_CART";
export const IS_DISPLAY_DELETE_MODAL = "IS_DISPLAY_DELETE_MODAL";
